/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TextSize } from "./types";
export namespace Components {
    interface LowText {
        /**
          * The font size.
         */
        "size": TextSize;
    }
}
declare global {
    interface HTMLLowTextElement extends Components.LowText, HTMLStencilElement {
    }
    var HTMLLowTextElement: {
        prototype: HTMLLowTextElement;
        new (): HTMLLowTextElement;
    };
    interface HTMLElementTagNameMap {
        "low-text": HTMLLowTextElement;
    }
}
declare namespace LocalJSX {
    interface LowText {
        /**
          * The font size.
         */
        "size"?: TextSize;
    }
    interface IntrinsicElements {
        "low-text": LowText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "low-text": LocalJSX.LowText & JSXBase.HTMLAttributes<HTMLLowTextElement>;
        }
    }
}
