/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TextFieldBehavior, TextSize, TextWeight } from "./types";
export namespace Components {
    interface LowText {
        /**
          * { item_description }
         */
        "contentAfter": string;
        /**
          * { item_description }
         */
        "contentBefore": string;
        /**
          * { item_description }
         */
        "size": TextSize;
        /**
          * { item_description }
         */
        "weight": TextWeight;
    }
    interface LowTextField {
        /**
          * { item_description }
         */
        "fieldName": string;
        /**
          * { item_description }
         */
        "fieldType": TextFieldBehavior;
        /**
          * { item_description }
         */
        "fieldValue": string;
        /**
          * { item_description }
         */
        "isClearable": boolean;
        /**
          * { item_description }
         */
        "isDisabled": boolean;
        /**
          * { item_description }
         */
        "isReadOnly": boolean;
        /**
          * { item_description }
         */
        "isRequired": boolean;
    }
}
export interface LowTextFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLowTextFieldElement;
}
declare global {
    interface HTMLLowTextElement extends Components.LowText, HTMLStencilElement {
    }
    var HTMLLowTextElement: {
        prototype: HTMLLowTextElement;
        new (): HTMLLowTextElement;
    };
    interface HTMLLowTextFieldElement extends Components.LowTextField, HTMLStencilElement {
    }
    var HTMLLowTextFieldElement: {
        prototype: HTMLLowTextFieldElement;
        new (): HTMLLowTextFieldElement;
    };
    interface HTMLElementTagNameMap {
        "low-text": HTMLLowTextElement;
        "low-text-field": HTMLLowTextFieldElement;
    }
}
declare namespace LocalJSX {
    interface LowText {
        /**
          * { item_description }
         */
        "contentAfter"?: string;
        /**
          * { item_description }
         */
        "contentBefore"?: string;
        /**
          * { item_description }
         */
        "size"?: TextSize;
        /**
          * { item_description }
         */
        "weight"?: TextWeight;
    }
    interface LowTextField {
        /**
          * { item_description }
         */
        "fieldName"?: string;
        /**
          * { item_description }
         */
        "fieldType"?: TextFieldBehavior;
        /**
          * { item_description }
         */
        "fieldValue"?: string;
        /**
          * { item_description }
         */
        "isClearable"?: boolean;
        /**
          * { item_description }
         */
        "isDisabled"?: boolean;
        /**
          * { item_description }
         */
        "isReadOnly"?: boolean;
        /**
          * { item_description }
         */
        "isRequired"?: boolean;
        /**
          * Emits the changed value.
         */
        "onChangeFieldValue"?: (event: LowTextFieldCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "low-text": LowText;
        "low-text-field": LowTextField;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "low-text": LocalJSX.LowText & JSXBase.HTMLAttributes<HTMLLowTextElement>;
            "low-text-field": LocalJSX.LowTextField & JSXBase.HTMLAttributes<HTMLLowTextFieldElement>;
        }
    }
}
